actor:
  activation: prelu
  alpha: 0.8 #0.5
  base_model: GCNConv
  beta2: 1
  beta3: 100.0
  drop: 0.1
  dropout_mlp: 0.1
  gate: 30
  homo: 0.3
  k1: 18
  lr: 0.0001
  lr_mlp: 0.001
  num: 300
  num_development: 6080
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 7350
  num_train_per_class: 20
  num_val: 150
  reg: 0.05
  seed: 42
  tau: 1.0
  wd_mlp: 0.0005
  weight_decay: 0.0005
chameleon:
  activation: prelu
  alpha: 0.7
  base_model: GCNConv
  beta2: 1
  beta3: 1000000.0
  drop: 0.1
  dropout_mlp: 0.3
  gate: 30
  homo: 0.4
  k1: 20
  lr: 0.0005
  lr_mlp: 0.005
  num: 300
  num_development: 1821
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 2027
  num_train_per_class: 20
  num_val: 150
  reg: 0.5
  seed: 42
  tau: 0.8
  wd_mlp: 0.0005
  weight_decay: 0.0005
citeseer:
  activation: prelu
  alpha: 0.5 #0.9
  base_model: GCNConv
  beta2: 1
  beta3: 1000.0
  drop: 0.3
  dropout_mlp: 0.3
  gate: 30
  homo: 0.3
  k1: 11
  lr: 0.0005
  lr_mlp: 0.0005
  num: 300
  num_development: 1500
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 3027
  num_train_per_class: 20
  num_val: 180
  reg: 0.5
  seed: 0
  tau: 1.5
  wd_mlp: 0.0005
  weight_decay: 0.0005
coauthor_cs:
  activation: prelu
  alpha: 0.5 # 1.0
  base_model: GCNConv
  beta2: 1
  beta3: 10.0
  drop: 0.1
  dropout_mlp: 0.4
  gate: 30
  homo: 0.5
  k1: 24
  lr: 0.0001
  lr_mlp: 0.0001
  num: 300
  num_development: 14666
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 17583
  num_train_per_class: 20
  num_val: 450
  reg: 1
  seed: 42
  tau: 0.2
  wd_mlp: 0.0005
  weight_decay: 0.0005
cora:
  activation: relu
  alpha: 0.5 # 0.1
  base_model: GCNConv
  beta2: 1
  beta3: 1000000.0
  drop: 0.3
  dropout_mlp: 0.3
  gate: 30
  homo: 0.6
  k1: 12
  lr: 0.0005
  lr_mlp: 0.01
  num: 300
  num_development: 1500
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 2358
  num_train_per_class: 20
  num_val: 210
  reg: 0.5
  seed: 39788
  tau: 0.8
  wd_mlp: 0.0005
  weight_decay: 0.0005
pubmed:
  activation: prelu
  alpha: 0.5
  base_model: GCNConv
  beta2: 1
  beta3: 100000.0
  drop: 0.2
  dropout_mlp: 0.3
  gate: 30
  homo: 0.4
  k1: 29
  lr: 0.001
  lr_mlp: 0.005
  num: 300
  num_development: 1500
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 19567
  num_train_per_class: 20
  num_val: 90
  reg: 1.5
  seed: 42
  tau: 0.8
  wd_mlp: 0.0005
  weight_decay: 0.0005
squirrel:
  activation: prelu
  alpha: 0.7
  base_model: GCNConv
  beta2: 1
  beta3: 100.0
  drop: 0.2
  dropout_mlp: 0.3
  gate: 30
  homo: 0.0
  k1: 28
  lr: 0.005
  lr_mlp: 0.001
  num: 300
  num_development: 4160
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 4951
  num_train_per_class: 20
  num_val: 150
  reg: 2
  seed: 42
  tau: 0.5
  wd_mlp: 0.0005
  weight_decay: 0.0005
ogbn-arxiv:
  activation: prelu
  alpha: 0.7
  base_model: GCNConv
  beta2: 1
  beta3: 100.0
  drop: 0.2
  dropout_mlp: 0.3
  gate: 30
  homo: 0.0
  k1: 28
  lr: 0.005
  lr_mlp: 0.001
  num: 300
  num_development: 135474
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 167343
  num_train_per_class: 20
  num_val: 1508
  reg: 2
  seed: 42
  tau: 0.5
  wd_mlp: 0.0005
  weight_decay: 0.0005
ogbn-proteins:
  activation: prelu
  alpha: 0.7
  base_model: GCNConv
  beta2: 1
  beta3: 100.0
  drop: 0.2
  dropout_mlp: 0.3
  gate: 30
  homo: 0.0
  k1: 28
  lr: 0.005
  lr_mlp: 0.001
  num: 300
  num_development: 106027
  num_epochs: 300
  num_hidden: 512
  num_proj_hidden: 512
  num_test: 132434
  num_train_per_class: 20
  num_val: 100
  reg: 2
  seed: 42
  tau: 0.5
  wd_mlp: 0.0005
  weight_decay: 0.0005